
import './globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import React from "react";
import {AppBar, Box, styled, Toolbar, Typography} from "@mui/material";
import Nav from "@/components/Nav";
import { createTheme } from '@mui/material/styles';
import {deepOrange, orange, purple} from '@mui/material/colors';
import {ThemeProvider} from "@mui/system";


const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}
//
// const StyledToolbar = styled(Toolbar)(
//
// )

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={inter.className}>


        {children}
        </body>
        </html>
    )
}
